import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer, BarChart } from 'recharts';
import { AlertTriangle, CheckCircle, GraduationCap, Globe, Lightbulb, ExternalLink, Printer, Mail, Download, Copy, Check } from 'lucide-react';

interface ResultsViewProps {
  data: AnalysisResult;
  language: 'en' | 'ar';
  t: any;
}

const ResultsView: React.FC<ResultsViewProps> = ({ data, language, t }) => {
  const isAr = language === 'ar';
  const [copied, setCopied] = useState(false);

  // Defensive check: ensure sectionScores is an array
  const sectionScores = data?.sectionScores || [];
  
  const chartData = sectionScores.map(s => ({
    subject: s.section,
    A: s.score,
    fullMark: 100,
  }));

  const handlePrint = () => {
    window.print();
  };

  const generateReportText = () => {
    // Defensive checks for all arrays
    const scores = data?.sectionScores || [];
    const gapAnalysis = data?.gapAnalysis || { missingComponents: [], weaknesses: [], strengths: [] };
    const missing = gapAnalysis.missingComponents || [];
    const weaknesses = gapAnalysis.weaknesses || [];
    const strengths = gapAnalysis.strengths || [];
    const recommendations = data?.recommendations || [];
    const revisedILOs = data?.revisedILOs || [];
    const benchmarks = data?.benchmarks || [];
    const tutors = data?.tutors || [];

    const scoresText = scores.map(s => `- ${s.section}: ${s.score}/100 (${s.feedback})`).join('\n');
    const gapsText = missing.length > 0 ? missing.join('\n- ') : t.noGaps;
    const weakText = weaknesses.length > 0 ? weaknesses.join('\n- ') : t.noGaps;
    const strengthText = strengths.length > 0 ? strengths.join('\n- ') : t.noGaps;
    const recommendationsText = recommendations.join('\n- ');
    const revisedIloText = revisedILOs.join('\n- ');
    const benchmarksText = benchmarks.map(b => `- ${b.university}: ${b.comparison}`).join('\n');
    const tutorsText = tutors.map(t => `- ${t.name} (${t.affiliation}): ${t.email}`).join('\n');

    return `
${t.uniName} - ${t.reportTitle}
---------------------------------------------------------
${t.university}: ${data.courseTitle}
${t.overallScore}: ${data.overallScore}/100

${t.breakdown.toUpperCase()}:
${scoresText}

---------------------------------------------------------
${t.criticalFindings.toUpperCase()}

${t.missing}:
- ${gapsText}

${t.weaknesses}:
- ${weakText}

${t.strengths}:
- ${strengthText}

---------------------------------------------------------
RECOMMENDATIONS:
- ${recommendationsText}

---------------------------------------------------------
${t.revisedILOs.toUpperCase()}:
- ${revisedIloText}

---------------------------------------------------------
${t.benchmarking.toUpperCase()}:
${benchmarksText}

---------------------------------------------------------
${t.tutors.toUpperCase()}:
${tutorsText}

---------------------------------------------------------
Generated by PAU Syllabus Evaluator
`;
  };

  const handleCopyReport = async () => {
    const text = generateReportText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleEmail = async () => {
    // 1. Generate Content
    const text = generateReportText();
    const subject = encodeURIComponent(`${t.reportTitle}: ${data.courseTitle}`);
    const summary = encodeURIComponent(
      `Course: ${data.courseTitle}\n${t.overallScore}: ${data.overallScore}/100\n\nPlease find the full detailed report copied in my clipboard or attached as PDF.`
    );

    try {
      // 2. Write to clipboard FIRST (Critical: Must happen before window.location or alert)
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);

      // 3. Show confirmation (This might block, so we do it after copy)
      await new Promise(resolve => setTimeout(resolve, 100));
      alert("The full report has been copied to your clipboard. You can now paste it into the email body.");

      // 4. Open Email Client
      window.location.href = `mailto:?subject=${subject}&body=${summary}`;
    } catch (err) {
      console.error("Clipboard write failed:", err);
      // Fallback
      alert("Could not auto-copy the report. Please use the Copy button manually.");
      window.location.href = `mailto:?subject=${subject}&body=${summary}`;
    }
  };

  const safeGapAnalysis = data?.gapAnalysis || { missingComponents: [], weaknesses: [], strengths: [] };
  const missingComponents = safeGapAnalysis.missingComponents || [];
  const weaknesses = safeGapAnalysis.weaknesses || [];
  const strengths = safeGapAnalysis.strengths || [];
  const revisedILOs = data?.revisedILOs || [];
  const suggestedActivities = data?.suggestedActivities || [];
  const benchmarks = data?.benchmarks || [];
  const tutors = data?.tutors || [];

  return (
    <div className={`w-full max-w-5xl mx-auto space-y-8 animate-fade-in ${isAr ? 'text-right font-arabic' : 'text-left'}`} dir={isAr ? 'rtl' : 'ltr'}>
      
      {/* Action Toolbar - Hidden on Print */}
      <div className="flex flex-wrap justify-end gap-3 no-print">
        <button 
            onClick={handleCopyReport}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition shadow-sm"
        >
            {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
            {copied ? t.copied : t.copyReport}
        </button>
        <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-lg hover:bg-slate-700 transition shadow-sm"
        >
            <Download className="w-4 h-4" />
            {t.downloadPdf}
        </button>
         <button 
            onClick={handleEmail}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition shadow-sm"
        >
            <Mail className="w-4 h-4" />
            {t.draftEmail}
        </button>
      </div>

      {/* Header Card */}
      <div className="bg-white rounded-xl shadow-lg border-t-4 border-blue-600 p-8 flex flex-col md:flex-row justify-between items-center gap-6 print:shadow-none print:border-slate-300">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">{data.courseTitle}</h1>
          <p className="text-slate-500 mt-1">{t.reportTitle}</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="text-right">
            <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider">{t.overallScore}</p>
            <p className={`text-4xl font-extrabold ${data.overallScore > 80 ? 'text-green-600' : data.overallScore > 60 ? 'text-yellow-500' : 'text-red-500'}`}>
              {data.overallScore}/100
            </p>
          </div>
          <div className="h-16 w-16 rounded-full border-4 border-slate-100 flex items-center justify-center bg-slate-50 print:hidden">
             <GraduationCap className="w-8 h-8 text-blue-600" />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 print:block print:space-y-6">
        
        {/* Section Scores Chart */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 print:break-inside">
          <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
            <span className="print:hidden"><BarChart className="w-5 h-5 text-purple-500" /></span> {t.breakdown}
          </h3>
          <div className="h-64 w-full chart-container">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="80%" data={chartData}>
                <PolarGrid />
                <PolarAngleAxis dataKey="subject" tick={{ fontSize: 12, fill: '#64748b' }} />
                <PolarRadiusAxis angle={30} domain={[0, 100]} />
                <Radar name="Score" dataKey="A" stroke="#2563eb" fill="#3b82f6" fillOpacity={0.6} isAnimationActive={false} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Gap Analysis */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 overflow-y-auto max-h-96 print:max-h-none print:break-inside">
            <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-orange-500" /> {t.criticalFindings}
            </h3>
            
            <div className="space-y-4">
                {/* Fallback if empty */}
                {missingComponents.length === 0 && 
                 weaknesses.length === 0 && 
                 strengths.length === 0 && (
                     <p className="text-slate-500 italic">{t.noGaps}</p>
                 )}

                {missingComponents.length > 0 && (
                    <div className="bg-red-50 p-4 rounded-lg border border-red-100 print:bg-white print:border-0">
                        <h4 className="font-semibold text-red-700 text-sm mb-2 print:text-black">{t.missing}</h4>
                        <ul className="list-disc list-inside text-sm text-red-600 space-y-1 print:text-slate-700">
                            {missingComponents.map((item, i) => <li key={i}>{item}</li>)}
                        </ul>
                    </div>
                )}
                
                {weaknesses.length > 0 && (
                    <div className="bg-yellow-50 p-4 rounded-lg border border-yellow-100 print:bg-white print:border-0">
                        <h4 className="font-semibold text-yellow-700 text-sm mb-2 print:text-black">{t.weaknesses}</h4>
                        <ul className="list-disc list-inside text-sm text-yellow-600 space-y-1 print:text-slate-700">
                             {weaknesses.map((item, i) => <li key={i}>{item}</li>)}
                        </ul>
                    </div>
                )}

                 {strengths.length > 0 && (
                    <div className="bg-green-50 p-4 rounded-lg border border-green-100 print:bg-white print:border-0">
                        <h4 className="font-semibold text-green-700 text-sm mb-2 print:text-black">{t.strengths}</h4>
                        <ul className="list-disc list-inside text-sm text-green-600 space-y-1 print:text-slate-700">
                             {strengths.map((item, i) => <li key={i}>{item}</li>)}
                        </ul>
                    </div>
                )}
            </div>
        </div>

      </div>

      {/* Revised ILOs & Activities */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 print:block print:space-y-6">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 print:break-inside">
             <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-green-500" /> {t.revisedILOs}
            </h3>
            {revisedILOs.length === 0 ? (
                <p className="text-sm text-slate-500">{t.noRevisions}</p>
            ) : (
                <ul className="space-y-3">
                    {revisedILOs.map((ilo, i) => (
                        <li key={i} className="flex gap-3 text-sm text-slate-700 p-3 bg-slate-50 rounded-lg print:bg-white print:p-0">
                            <span className="font-bold text-blue-500">{i+1}.</span>
                            {ilo}
                        </li>
                    ))}
                </ul>
            )}
        </div>

         <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 print:break-inside">
             <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                <Lightbulb className="w-5 h-5 text-yellow-500" /> {t.activities}
            </h3>
             {suggestedActivities.length === 0 ? (
                <p className="text-sm text-slate-500">{t.noActivities}</p>
            ) : (
                <div className="space-y-3">
                    {suggestedActivities.map((act, i) => (
                        <div key={i} className="p-3 bg-yellow-50/50 border border-yellow-100 rounded-lg print:bg-white print:border-slate-200">
                            <h4 className="font-bold text-slate-800 text-sm">{act.title}</h4>
                            <p className="text-xs text-slate-600 mt-1">{act.description}</p>
                            <div className="mt-2 text-[10px] uppercase tracking-wide text-slate-400 font-semibold bg-white inline-block px-2 py-1 rounded border">
                                {t.alignsWith}: {act.learningOutcomeMap}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
      </div>

      {/* Benchmarking */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 print:break-inside">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
            <Globe className="w-5 h-5 text-blue-500" /> {t.benchmarking}
        </h3>
        <div className="overflow-x-auto">
            <table className="w-full text-sm text-left text-slate-600">
                <thead className="text-xs text-slate-700 uppercase bg-slate-50 print:bg-slate-200">
                    <tr>
                        <th className="px-6 py-3">{t.university}</th>
                        <th className="px-6 py-3">{t.comparison}</th>
                    </tr>
                </thead>
                <tbody>
                    {benchmarks.map((bm, i) => (
                        <tr key={i} className="bg-white border-b hover:bg-slate-50 print:border-slate-300">
                            <td className="px-6 py-4 font-medium text-slate-900">
                                {bm.university}
                                {bm.url && (
                                    <a href={bm.url} target="_blank" rel="noreferrer" className="ml-2 inline-block text-blue-500 hover:text-blue-700 no-print">
                                        <ExternalLink className="w-3 h-3" />
                                    </a>
                                )}
                            </td>
                            <td className="px-6 py-4">{bm.comparison}</td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
      </div>

       {/* Tutors */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 mb-10 print:break-inside">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
            <GraduationCap className="w-5 h-5 text-indigo-500" /> {t.tutors}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {tutors.length === 0 ? (
                <p className="text-slate-500 text-sm col-span-3 text-center py-4">{t.noTutors}</p>
            ) : (
                tutors.map((tutor, i) => (
                    <div key={i} className="p-4 border rounded-lg bg-indigo-50/30 border-indigo-100 hover:shadow-md transition print:bg-white print:border-slate-300">
                        <h4 className="font-bold text-slate-900">{tutor.name}</h4>
                        <p className="text-xs text-indigo-600 font-medium mb-2 print:text-black">{tutor.affiliation}</p>
                        <p className="text-xs text-slate-600 mb-2 line-clamp-2 print:line-clamp-none">{tutor.specialization}</p>
                        <p className="text-xs text-slate-500 break-all">
                            {tutor.email || t.emailNotListed}
                        </p>
                    </div>
                ))
            )}
        </div>
      </div>

    </div>
  );
};

export default ResultsView;